# Generated by Django 3.0.3 on 2020-07-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('danger', 'veryhigh'), ('warning', 'high'), ('info', 'normal'), ('success', 'low')], max_length=50)),
                ('duedate', models.DateField()),
            ],
        ),
    ]
