# Generated by Django 3.0.3 on 2020-07-23 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todomodel',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'veryhigh'), ('warning', 'high'), ('info', 'normal'), ('success', 'low')], max_length=50, verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タスク名'),
        ),
    ]
